print('     ggggggg          l      ')
print('    g       g        l       ')
print('   g                l        ')
print('  g     ggg        l         ')
print(' g       g        l          ')
print('g       g        l           ')
print(' ggggggg         lllllll     ')